name: bug report
description: something went wrong
body:
  - type: textarea
    id: freeform
    attributes:
      label: describe your issue
      placeholder: 'I was doing ... I ran ... I expected ... I got ...'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: pre-commit --version
      placeholder: pre-commit x.x.x
    validations:
      required: false
